server:
  port: 8090

spring:
  application:
    name: USER-SERVICE

  zipkin:
    base-url: http://127.0.0.1:9411/

  datasource:
    url: jdbc:h2:mem:mydb
    username: prince
    password: 12345
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    spring.jpa.hibernate.ddl-auto: update
  h2:
    console.enabled: true

  cloud:
    loadbalancer:
     ribbon:
      enabled: false
      instance: 
          name: ribbon-server
          server: localhost:9090,localhost:9091,localhost:9092
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#     # defaultZone: http://localhost:8787/eureka
#      defaultZone: http://localhost:8761/eureka/
#      instance:
#        hostname: localhost