server:
  port : 8989

spring:
  application:
    name: CONFIG-SERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/princeraikwar007/config-server
          clone-on-start: true
          default-label: main